name: przepisy_sylwii_mobile
description: Mobile recipe app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.8
  firebase_storage: ^11.0.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6+2
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  lottie: ^2.2.0
  package_info_plus: ^3.0.2
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/images/splash_logo.png'
  android_12:
    color: '#FFFFFF'
    image: 'assets/images/splash_logo.png'

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo_background.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - config/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
