name: przepisy_sylwii_mobile
description: Mobile recipe app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.0
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - config/
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
